# Generated by Django 4.1 on 2022-08-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
